// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Activities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7154fdcf-6670-48d7-a588-cc29a986eb51"),
                            Category = "Drinks",
                            City = "Washington D.C.",
                            Date = new DateTime(2023, 10, 27, 21, 14, 43, 316, DateTimeKind.Utc).AddTicks(6927),
                            Description = "Activity 3 months ago",
                            Title = "Past Activity 1",
                            Venue = "U st"
                        },
                        new
                        {
                            Id = new Guid("5d16d4a0-21b6-44ac-afe0-bc7e65e22bc3"),
                            Category = "Dating",
                            City = "Tampa",
                            Date = new DateTime(2024, 3, 27, 21, 14, 43, 316, DateTimeKind.Utc).AddTicks(6950),
                            Description = "Activity 1, 2 months in the future",
                            Title = "Future Activity 1",
                            Venue = "Armiturworks"
                        },
                        new
                        {
                            Id = new Guid("34d37a6b-8fae-4d76-bfd2-55aa45680241"),
                            Category = "Festive",
                            City = "Atlanta",
                            Date = new DateTime(2023, 11, 27, 21, 14, 43, 316, DateTimeKind.Utc).AddTicks(6959),
                            Description = "Activity 2, 2 months ago",
                            Title = "Past Activity 2",
                            Venue = "YSL HQ"
                        },
                        new
                        {
                            Id = new Guid("630e212d-7c6d-4599-b1f7-f390afd1e60d"),
                            Category = "Social",
                            City = "Shirlington",
                            Date = new DateTime(2024, 3, 27, 21, 14, 43, 316, DateTimeKind.Utc).AddTicks(6984),
                            Description = "Activity 2, 2 months in future",
                            Title = "Future Activity 2",
                            Venue = "Pallette22"
                        },
                        new
                        {
                            Id = new Guid("b2506493-1861-4c9a-9985-dc8296f84d83"),
                            Category = "Sports",
                            City = "San Diego",
                            Date = new DateTime(2024, 5, 27, 21, 14, 43, 316, DateTimeKind.Utc).AddTicks(6991),
                            Description = "Activity 3, 4 months in future",
                            Title = "Future Activity 3",
                            Venue = "Aztecs Stadium"
                        },
                        new
                        {
                            Id = new Guid("f872ea99-c733-4f57-9caf-df229624be40"),
                            Category = "Dating",
                            City = "Los Angeles",
                            Date = new DateTime(2023, 8, 27, 21, 14, 43, 316, DateTimeKind.Utc).AddTicks(6997),
                            Description = "Activity 2, 5 months ago",
                            Title = "Past Activity 3",
                            Venue = "Staples Center"
                        },
                        new
                        {
                            Id = new Guid("9dc301c9-a87c-4081-a68a-d2a91a3d7d74"),
                            Category = "Social",
                            City = "Arlington",
                            Date = new DateTime(2024, 1, 29, 21, 14, 43, 316, DateTimeKind.Utc).AddTicks(7002),
                            Description = "Activity 4, 2 days in future",
                            Title = "Future Activity 4",
                            Venue = "UpaDidi"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
